#!/usr/bin/env bash
# ============================================================
# clean_capcut_cache.sh — CapCut cache cleaner for macOS
# ============================================================
# Usage:
#   ./clean_capcut_cache.sh          — dry run (show what would be deleted)
#   ./clean_capcut_cache.sh --clean  — actually delete cache
# ============================================================

set -euo pipefail

DRY_RUN=true
if [[ "${1:-}" == "--clean" ]]; then
    DRY_RUN=false
fi

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

echo ""
echo -e "${BOLD}=== CapCut Cache Cleaner ===${RESET}"
echo ""

# ── 1. macOS version check ───────────────────────────────────
OS_NAME=$(sw_vers -productName)
OS_VER=$(sw_vers -productVersion)
BUILD=$(sw_vers -buildVersion)
MAJOR=$(echo "$OS_VER" | cut -d. -f1)

echo -e "${CYAN}System:${RESET} $OS_NAME $OS_VER (Build $BUILD)"

if [[ "$MAJOR" -lt 12 ]]; then
    echo -e "${RED}Warning: This script is tested on macOS 12+. Detected $OS_VER — proceed with caution.${RESET}"
fi

# ── 2. Check if CapCut is running ────────────────────────────
if pgrep -x "CapCut" > /dev/null 2>&1; then
    echo ""
    echo -e "${RED}CapCut is currently running!${RESET}"
    echo -e "Please quit CapCut before cleaning cache to avoid corruption."
    echo -e "Run:  ${YELLOW}osascript -e 'quit app \"CapCut\"'${RESET}"
    exit 1
fi
echo -e "${GREEN}CapCut is not running. Safe to clean.${RESET}"
echo ""

# ── 3. Cache locations ───────────────────────────────────────
CAPCUT_CACHE_DIR="$HOME/Movies/CapCut/User Data/Cache"
CONTAINER_CACHE="$HOME/Library/Containers/com.lemon.lvoverseas/Data/Library/Caches"
CONTAINER_TMP="$HOME/Library/Containers/com.lemon.lvoverseas/Data/tmp"
CAPCUT_LOGS="$HOME/Movies/CapCut/User Data/Log"
CAPCUT_VELOGS="$HOME/Movies/CapCut/User Data/VELog"
CAPCUT_CRASH="$HOME/Movies/CapCut/User Data/Crash"

# Cache subdirs that are safe to wipe (will be regenerated by CapCut)
SAFE_CACHE_SUBDIRS=(
    "SmartCrop"
    "frameThumbnail"
    "effect"
    "audioWave"
    "VENetworkPlayer"
    "image"
    "GeckoCpp"
    "AigcMaterailCache"
    "strategy"
    "ILASDKDB"
    "importcache3"
    "bytebench"
    "template"
    "C2PACache"
    "AudioFunction"
    "tts"
    "ttsTemp"
    "stable"
    "AlgorithmCache"
    "music"
    "agencycache"
    "ressdk_db"
    "tryInputText"
)

# ── 4. Calculate sizes ───────────────────────────────────────
echo -e "${BOLD}Cache sizes before cleaning:${RESET}"
echo "────────────────────────────────────────"

TOTAL_BYTES=0

measure() {
    local path="$1"
    local label="$2"
    if [[ -d "$path" ]]; then
        local size
        size=$(du -sh "$path" 2>/dev/null | cut -f1)
        local bytes
        bytes=$(du -sk "$path" 2>/dev/null | cut -f1)
        printf "  %-52s %s\n" "$label" "$size"
        TOTAL_BYTES=$((TOTAL_BYTES + bytes))
    fi
}

for subdir in "${SAFE_CACHE_SUBDIRS[@]}"; do
    measure "$CAPCUT_CACHE_DIR/$subdir" "Cache/$subdir"
done

measure "$CONTAINER_CACHE" "Container Caches (system)"
measure "$CONTAINER_TMP"   "Container tmp"
measure "$CAPCUT_LOGS"     "Logs"
measure "$CAPCUT_VELOGS"   "VELogs"
measure "$CAPCUT_CRASH"    "Crash reports"

echo "────────────────────────────────────────"
TOTAL_MB=$(echo "scale=1; $TOTAL_BYTES / 1024" | bc)
TOTAL_GB=$(echo "scale=2; $TOTAL_BYTES / 1048576" | bc)
echo -e "  ${BOLD}Total reclaimable: ~${TOTAL_MB} MB (${TOTAL_GB} GB)${RESET}"
echo ""

# ── 5. Dry run / actual clean ────────────────────────────────
delete_dir_contents() {
    local path="$1"
    if [[ ! -d "$path" ]]; then return; fi
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY RUN]${RESET} Would delete contents of: $path"
    else
        echo -e "  ${GREEN}Cleaning:${RESET} $path"
        rm -rf "${path:?}"/*  2>/dev/null || true
    fi
}

delete_dir() {
    local path="$1"
    if [[ ! -d "$path" ]]; then return; fi
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY RUN]${RESET} Would delete: $path"
    else
        echo -e "  ${GREEN}Deleting:${RESET} $path"
        rm -rf "${path:?}"
    fi
}

if $DRY_RUN; then
    echo -e "${YELLOW}DRY RUN MODE — nothing will be deleted.${RESET}"
    echo -e "Run with ${BOLD}--clean${RESET} flag to actually delete.\n"
else
    echo -e "${GREEN}Cleaning CapCut cache...${RESET}\n"
fi

# Clean cache subdirectories (keep the folder, delete contents)
for subdir in "${SAFE_CACHE_SUBDIRS[@]}"; do
    delete_dir_contents "$CAPCUT_CACHE_DIR/$subdir"
done

# Clean container caches
delete_dir_contents "$CONTAINER_CACHE"
delete_dir_contents "$CONTAINER_TMP"

# Clean logs and crash reports
delete_dir_contents "$CAPCUT_LOGS"
delete_dir_contents "$CAPCUT_VELOGS"
delete_dir_contents "$CAPCUT_CRASH"

# ── 6. Done ─────────────────────────────────────────────────
echo ""
if $DRY_RUN; then
    echo -e "${YELLOW}Dry run complete. Run with --clean to free ~${TOTAL_MB} MB.${RESET}"
else
    # Show freed space
    echo -e "${GREEN}Done! Reclaimed approximately ${TOTAL_MB} MB (${TOTAL_GB} GB).${RESET}"
    echo ""
    echo -e "${CYAN}Note:${RESET} CapCut will rebuild its cache the next time you open a project."
    echo -e "      Your projects, presets, and downloaded resources are untouched."
fi
echo ""
