#!/usr/bin/env python3
"""
render_video_videos.py — Export YouTube + TikTok chapter videos from Grok scene MP4 clips.

Stitches scene MP4 clips (generated by generate_video.py) in sequence with the
chapter narration audio. A static thumbnail image is used as a 5s intro card.

For each chapter folder the script expects:
  • *_NN_thumb.(png|jpg|webp)  — static intro card (first 5s)
  • *_NN_scene.mp4              — Grok video clips (stitched in order)
  • narration audio (.mp3/.m4a/.aac/.wav/.flac)

Output:
  • <stem>_youtube.mp4  — 1440×2560 (2K), av1_qsv / hevc_videotoolbox, 24 fps
  • <stem>_tiktok.mp4   — 1080×1920,       h264_qsv / h264_videotoolbox, 30 fps

Usage:
    python render_video_videos.py /path/to/folder

─────────────────────────────────────────────────────────────────────────────
Intel Arc A750 QSV — Pipeline Rules (DO NOT CHANGE without reading this)
─────────────────────────────────────────────────────────────────────────────
(See render_video_images.py header for full QSV rules)

Key notes for video concat pipeline:
  - Each scene MP4 clip is loop-trimmed to fill the audio (using -stream_loop -1
    on the remote path and a concat+trim approach locally).
  - No xfade transitions — clips are stitched sequentially (cut-to-cut).
  - Ambient audio from scene clips is mixed at 7% volume under narration.
─────────────────────────────────────────────────────────────────────────────
"""

import sys
import json
import re
import subprocess
import time
import argparse
import requests
from pathlib import Path

RENDER_SERVER_URL = "http://192.168.0.14:8765"

LOCAL_CODEC_YT = {
    "fps": 24, "cv": "hevc_videotoolbox", "bv": "4M",
    "ba": "256k", "pix_fmt": "yuv420p", "allow_sw": True, "q_v": 55,
}
LOCAL_CODEC_TT = {
    "fps": 30, "cv": "h264_videotoolbox", "bv": "5M",
    "ba": "192k", "pix_fmt": "yuv420p", "allow_sw": True, "q_v": 60,
}

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
AUDIO_EXTENSIONS = {".mp3", ".m4a", ".aac", ".wav", ".flac"}
AMBIENT_VOL = 0.07   # Grok video ambient audio: 7% under narration

MIME_MAP = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".mp4": "video/mp4",
    ".mp3": "audio/mpeg", ".m4a": "audio/mp4",
    ".aac": "audio/aac", ".wav": "audio/wav", ".flac": "audio/flac",
}

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def get_audio_duration(audio_path: Path) -> float:
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", str(audio_path)],
            capture_output=True, text=True, check=True
        )
        return float(json.loads(r.stdout)["format"]["duration"])
    except Exception:
        r = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_streams", str(audio_path)],
            capture_output=True, text=True, check=True
        )
        data = json.loads(r.stdout)
        for s in data.get("streams", []):
            if "duration" in s:
                return float(s["duration"])
    raise ValueError(f"Could not read audio duration for {audio_path.name}")


def find_thumb_image(folder: Path):
    """Find the _NN_thumb image file (PNG/JPG/WebP)."""
    for f in sorted(folder.iterdir()):
        if not f.is_file():
            continue
        if re.search(r'_\d+_thumb\.(png|jpg|jpeg|webp)$', f.name.lower()):
            return f
    return None


def find_scene_mp4s(folder: Path) -> list:
    """Find all _NN_scene.mp4 files sorted by NN."""
    clips = []
    for f in sorted(folder.iterdir()):
        if not f.is_file():
            continue
        m = re.search(r'_(\d+)_scene\.mp4$', f.name.lower())
        if m:
            clips.append((int(m.group(1)), f))
    clips.sort(key=lambda x: x[0])
    return [f for _, f in clips]


def human_size(p: Path):
    s = p.stat().st_size
    for u in ["B", "KB", "MB", "GB"]:
        if s < 1024:
            return f"{s:.1f} {u}"
        s /= 1024
    return f"{s:.1f} TB"


def check_server_with_retries(n: int = 3) -> bool:
    for attempt in range(1, n + 1):
        print(f"  [attempt {attempt}/{n}] Contacting render server...")
        try:
            resp = requests.get(f"{RENDER_SERVER_URL}/health", timeout=3)
            if resp.headers is not None:
                print("  Render server online.")
                return True
        except Exception:
            pass
        print(f"  Attempt {attempt} failed.")
        if attempt < n:
            time.sleep(2)
    print(f"  Render server unreachable after {n} attempts.")
    return False


# ─────────────────────────────────────────────────────────────────────────────
# Build FFmpeg command
# ─────────────────────────────────────────────────────────────────────────────
#
# Layout:
#   [0]     : thumb image → static 5s intro at output resolution
#   [1..N]  : scene MP4 clips, each looped to fill its segment
#
# The clips are divided equally across (duration - 5s). Each clip is looped
# and trimmed to its allocated time. Cuts are sharp (no xfade — stitched in
# sequence per user request).
#
# Audio:
#   Each video clip contributes ambient audio at AMBIENT_VOL (7%), crossfaded
#   at segment boundaries and mixed under the narration track.

def _build_filter_remote(thumb_path: Path, scene_clips: list, fps: int,
                          out_w: int, out_h: int, duration: float):
    """Build -filter_complex and -i args for remote (QSV) render."""
    THUMB_DUR = 5.0
    n_clips = len(scene_clips)
    if n_clips == 0:
        raise ValueError("No scene clips to render.")

    clip_dur = (duration - THUMB_DUR) / n_clips   # seconds per clip

    # Input list: [thumb_img] + [clip_0, clip_1, ..., clip_N-1] + [audio]
    # thumb is index 0 (static image, looped at fps)
    # clips are indices 1..N (video, stream-looped)
    # audio is index N+1

    filter_parts = []

    # Scale thumb → output resolution
    filter_parts.append(
        f"[0:v]"
        f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
        f"crop={out_w}:{out_h},setsar=1,fps={fps},"
        f"trim=duration={THUMB_DUR:.3f},"
        f"format=yuv420p[vthumb]"
    )

    # Scale and trim each scene clip
    for i, _ in enumerate(scene_clips):
        inp = i + 1   # input index (0=thumb, 1..N=clips)
        filter_parts.append(
            f"[{inp}:v]"
            f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
            f"crop={out_w}:{out_h},setsar=1,fps={fps},"
            f"trim=duration={clip_dur:.3f},setpts=PTS-STARTPTS,"
            f"format=yuv420p[vclip{i}]"
        )

    # Concatenate all video segments
    all_segs = "[vthumb]" + "".join(f"[vclip{i}]" for i in range(n_clips))
    n_total = 1 + n_clips
    filter_parts.append(
        f"{all_segs}concat=n={n_total}:v=1:a=0,"
        f"format=nv12[outv]"
    )

    # Ambient audio: trim each clip's audio to its segment duration, then concat
    for i, _ in enumerate(scene_clips):
        inp = i + 1
        filter_parts.append(
            f"[{inp}:a]atrim=duration={clip_dur:.3f},asetpts=PTS-STARTPTS[va{i}]"
        )

    # Silence for thumb intro duration
    filter_parts.append(
        f"anullsrc=r=44100:cl=stereo,"
        f"atrim=duration={THUMB_DUR:.3f},"
        f"asetpts=PTS-STARTPTS[vathumb]"
    )

    # Concat all audio segments (thumb silence + clip ambients)
    audio_segs = "[vathumb]" + "".join(f"[va{i}]" for i in range(n_clips))
    filter_parts.append(
        f"{audio_segs}concat=n={n_total}:v=0:a=1[ambraw]"
    )

    # Mix ambient under narration
    narration_idx = n_clips + 1  # input index
    fade_out_st = max(0.0, duration - 3.0)
    filter_parts.append(f"[ambraw]volume={AMBIENT_VOL}[ambient]")
    filter_parts.append(
        f"[{narration_idx}:a][ambient]"
        f"amix=inputs=2:normalize=0:duration=first:dropout_transition=0[mixed]"
    )
    filter_parts.append(
        f"[mixed]"
        f"afade=t=in:st=0:d=2,"
        f"afade=t=out:st={fade_out_st:.3f}:d=3[aout]"
    )

    return ";".join(filter_parts)


def _build_filter_local(thumb_path: Path, scene_clips: list, fps: int,
                         out_w: int, out_h: int, duration: float):
    """Build -filter_complex for local (VideoToolbox) render — same logic, yuv420p output."""
    THUMB_DUR = 5.0
    n_clips = len(scene_clips)
    clip_dur = (duration - THUMB_DUR) / n_clips

    filter_parts = []

    filter_parts.append(
        f"[0:v]"
        f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
        f"crop={out_w}:{out_h},setsar=1,fps={fps},"
        f"trim=duration={THUMB_DUR:.3f},"
        f"format=yuv420p[vthumb]"
    )

    for i, _ in enumerate(scene_clips):
        inp = i + 1
        filter_parts.append(
            f"[{inp}:v]"
            f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
            f"crop={out_w}:{out_h},setsar=1,fps={fps},"
            f"trim=duration={clip_dur:.3f},setpts=PTS-STARTPTS,"
            f"format=yuv420p[vclip{i}]"
        )

    all_segs = "[vthumb]" + "".join(f"[vclip{i}]" for i in range(n_clips))
    n_total = 1 + n_clips
    filter_parts.append(
        f"{all_segs}concat=n={n_total}:v=1:a=0,"
        f"format=yuv420p[outv]"
    )

    for i, _ in enumerate(scene_clips):
        inp = i + 1
        filter_parts.append(
            f"[{inp}:a]atrim=duration={clip_dur:.3f},asetpts=PTS-STARTPTS[va{i}]"
        )

    filter_parts.append(
        f"anullsrc=r=44100:cl=stereo,"
        f"atrim=duration={THUMB_DUR:.3f},"
        f"asetpts=PTS-STARTPTS[vathumb]"
    )

    audio_segs = "[vathumb]" + "".join(f"[va{i}]" for i in range(n_clips))
    filter_parts.append(
        f"{audio_segs}concat=n={n_total}:v=0:a=1[ambraw]"
    )

    narration_idx = n_clips + 1
    fade_out_st = max(0.0, duration - 3.0)
    filter_parts.append(f"[ambraw]volume={AMBIENT_VOL}[ambient]")
    filter_parts.append(
        f"[{narration_idx}:a][ambient]"
        f"amix=inputs=2:normalize=0:duration=first:dropout_transition=0[mixed]"
    )
    filter_parts.append(
        f"[mixed]"
        f"afade=t=in:st=0:d=2,"
        f"afade=t=out:st={fade_out_st:.3f}:d=3[aout]"
    )

    return ";".join(filter_parts)


def build_render_job(thumb: Path, scene_clips: list, audio: Path, duration: float,
                     out_w: int, out_h: int, codec_info: dict):
    """Build remote render job (server uses {input_N} placeholders)."""
    # Inputs: thumb(0), clip_0(1)..clip_N(N), audio(N+1)
    all_uploads = [thumb] + scene_clips + [audio]
    n_clips = len(scene_clips)

    cmd_inputs = ["-r", str(codec_info["fps"]), "-loop", "1", "-i", "{input_0}"]
    for i in range(n_clips):
        cmd_inputs += ["-stream_loop", "-1", "-i", f"{{input_{i+1}}}"]
    cmd_inputs += ["-i", f"{{input_{n_clips+1}}}"]

    fc = _build_filter_remote(thumb, scene_clips, codec_info["fps"], out_w, out_h, duration)
    # Replace absolute Path objects in filter with placeholders (paths are not embedded in filter)

    cmd = ["-y", "-filter_threads", "8"]
    cmd += cmd_inputs
    cmd += ["-filter_complex", fc, "-map", "[outv]", "-map", "[aout]"]
    cmd += [
        "-c:v", codec_info["cv"],
        "-preset", codec_info.get("preset", "slow"),
        "-b:v", codec_info["bv"],
    ]
    if codec_info.get("profile"):
        cmd += ["-profile:v", codec_info["profile"]]
    if codec_info.get("level"):
        cmd += ["-level:v", codec_info["level"]]
    cmd += [
        "-c:a", "aac",
        "-b:a", codec_info["ba"],
        "-ar", "48000",
        "-t", str(duration),
        "-movflags", "+faststart",
        "{output_0}",
    ]
    return cmd, all_uploads


def build_local_render_job(thumb: Path, scene_clips: list, audio: Path, duration: float,
                            out_w: int, out_h: int, codec_info: dict, output_path: Path) -> list:
    """Build local ffmpeg command (VideoToolbox)."""
    n_clips = len(scene_clips)

    cmd_inputs = ["-r", str(codec_info["fps"]), "-loop", "1", "-i", str(thumb)]
    for clip in scene_clips:
        cmd_inputs += ["-stream_loop", "-1", "-i", str(clip)]
    cmd_inputs += ["-i", str(audio)]

    fc = _build_filter_local(thumb, scene_clips, codec_info["fps"], out_w, out_h, duration)

    cmd = ["ffmpeg", "-y", "-filter_threads", "4"]
    cmd += cmd_inputs
    cmd += ["-filter_complex", fc, "-map", "[outv]", "-map", "[aout]"]
    cmd += [
        "-c:v", codec_info["cv"],
        "-b:v", codec_info["bv"],
        "-q:v", str(codec_info["q_v"]),
    ]
    if codec_info.get("allow_sw"):
        cmd += ["-allow_sw", "1"]
    cmd += [
        "-pix_fmt", codec_info["pix_fmt"],
        "-c:a", "aac",
        "-b:a", codec_info["ba"],
        "-ar", "48000",
        "-t", str(duration),
        "-movflags", "+faststart",
        str(output_path),
    ]
    return cmd


# ─────────────────────────────────────────────────────────────────────────────
# Server Execution
# ─────────────────────────────────────────────────────────────────────────────

def render_on_server(job_cmd: list, unique_uploads: list, output_filename: str,
                     output_path: Path, duration: float):
    file_handles = []
    multipart_files = []
    job_id = None
    try:
        for fpath in unique_uploads:
            mime = MIME_MAP.get(fpath.suffix.lower(), "application/octet-stream")
            fh = open(fpath, "rb")
            file_handles.append(fh)
            multipart_files.append(("files", (fpath.name, fh, mime)))

        resp = requests.post(f"{RENDER_SERVER_URL}/render", files=multipart_files, timeout=120, data={
            "command": json.dumps(job_cmd),
            "outputs": json.dumps([output_filename]),
            "duration": str(duration),
        })
        resp.raise_for_status()
        job_id = resp.json()["job_id"]

        last_pct = -1
        while True:
            r = requests.get(f"{RENDER_SERVER_URL}/status/{job_id}", timeout=10)
            data = r.json()
            st = data["status"]
            pct = data.get("progress", 0)
            if pct != last_pct:
                bar = "#" * int(40 * pct / 100) + "-" * (40 - int(40 * pct / 100))
                print(f"\r  [{bar}] {pct:3d}%  {data.get('render_time_seconds', 0):.1f}s", end="", flush=True)
                last_pct = pct
            if st == "done":
                print()
                break
            elif st == "failed":
                print()
                raise RuntimeError(f"Server Render Exception: {data.get('error')}")
            time.sleep(2)

        print(f"  Downloading remote output -> {output_path.name}")
        dl_resp = requests.get(f"{RENDER_SERVER_URL}/download/{job_id}/{output_filename}", stream=True)
        dl_resp.raise_for_status()
        with open(output_path, "wb") as f:
            for chunk in dl_resp.iter_content(chunk_size=1024 * 1024):
                f.write(chunk)
    finally:
        for fh in file_handles:
            fh.close()
        if job_id:
            try:
                requests.delete(f"{RENDER_SERVER_URL}/job/{job_id}", timeout=5)
            except Exception:
                pass


def render_locally(cmd: list, duration: float):
    proc = subprocess.Popen(cmd, stderr=subprocess.PIPE, text=True, bufsize=1)
    time_pattern = re.compile(r'time=(\d{2}):(\d{2}):(\d{2})\.(\d{2})')
    last_pct = -1
    for line in proc.stderr:
        m = time_pattern.search(line)
        if m and duration > 0:
            h, mn, s, cs = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
            elapsed = h * 3600 + mn * 60 + s + cs / 100.0
            pct = min(100, int(elapsed / duration * 100))
            if pct != last_pct:
                bar = "#" * int(40 * pct / 100) + "-" * (40 - int(40 * pct / 100))
                print(f"\r  [{bar}] {pct:3d}%  {elapsed:.1f}s", end="", flush=True)
                last_pct = pct
    proc.wait()
    print()
    if proc.returncode != 0:
        raise RuntimeError(f"Local FFmpeg render failed (exit {proc.returncode})")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate YouTube + TikTok chapter videos from Grok scene MP4 clips."
    )
    parser.add_argument("folder", help="Chapter output folder")
    args = parser.parse_args()

    folder = Path(args.folder).expanduser().resolve()

    print(f"\nAnalyzing: {folder}")

    use_remote = check_server_with_retries(3)
    if not use_remote:
        print("  Falling back to local render (Apple VideoToolbox — Mac Mini M2).")

    audio = next((f for f in folder.iterdir() if f.suffix.lower() in AUDIO_EXTENSIONS), None)
    if not audio:
        print("Error: Audio missing.")
        sys.exit(1)

    thumb = find_thumb_image(folder)
    if not thumb:
        print("Error: No thumbnail image (_NN_thumb.png/jpg/webp) found.")
        sys.exit(1)

    scene_clips = find_scene_mp4s(folder)
    if not scene_clips:
        print("Error: No scene MP4 clips (_NN_scene.mp4) found.")
        print("  Run generate_video.py first to generate Grok video clips.")
        sys.exit(1)

    duration = get_audio_duration(audio)
    clip_dur = (duration - 5.0) / len(scene_clips)

    print(f"\n  Audio    : {audio.name} ({duration / 60:.1f} min)")
    print(f"  Thumb    : {thumb.name}")
    print(f"  Clips    : {len(scene_clips)} scene MP4(s), ~{clip_dur:.1f}s each")
    for i, c in enumerate(scene_clips):
        print(f"    [{i+1}] {c.name}")

    stem = re.sub(r'_\d+_(thumb|scene).*', '', thumb.stem)
    out_yt = folder / f"{stem}_youtube.mp4"
    out_tt = folder / f"{stem}_tiktok.mp4"

    if out_yt.exists():
        print(f"  Skipping YouTube render — {out_yt.name} already exists.")
    if out_tt.exists():
        print(f"  Skipping TikTok render  — {out_tt.name} already exists.")
    yt_req = not out_yt.exists()
    tt_req = not out_tt.exists()

    if yt_req:
        if use_remote:
            print(f"\n[1/2] YouTube Rendering | 1440x2560 (2K) | av1_qsv | 24 FPS  [REMOTE]")
            cmd, files = build_render_job(thumb, scene_clips, audio, duration, 1440, 2560, {
                "fps": 24, "cv": "av1_qsv", "bv": "3M", "ba": "256k", "preset": "4"
            })
            render_on_server(cmd, files, out_yt.name, out_yt, duration)
        else:
            print(f"\n[1/2] YouTube Rendering | 1440x2560 (2K) | hevc_videotoolbox | 24 FPS  [LOCAL]")
            cmd = build_local_render_job(thumb, scene_clips, audio, duration, 1440, 2560, LOCAL_CODEC_YT, out_yt)
            render_locally(cmd, duration)
        print(f"  Saved: {human_size(out_yt)}")

    if tt_req:
        if use_remote:
            print(f"\n[2/2] TikTok Rendering | 1080x1920 | h264_qsv | 30 FPS  [REMOTE]")
            cmd, files = build_render_job(thumb, scene_clips, audio, duration, 1080, 1920, {
                "fps": 30, "cv": "h264_qsv", "bv": "5M", "ba": "192k",
                "profile": "high", "level": "4.1"
            })
            render_on_server(cmd, files, out_tt.name, out_tt, duration)
        else:
            print(f"\n[2/2] TikTok Rendering | 1080x1920 | h264_videotoolbox | 30 FPS  [LOCAL]")
            cmd = build_local_render_job(thumb, scene_clips, audio, duration, 1080, 1920, LOCAL_CODEC_TT, out_tt)
            render_locally(cmd, duration)
        print(f"  Saved: {human_size(out_tt)}")


if __name__ == "__main__":
    main()
