#!/usr/bin/env python3
"""
render_video_images.py — Export YouTube + TikTok chapter videos using static scene images.

Uses static PNG/JPG/WebP scene images generated by Gemini (via generate_image.py).
No video clips — no ambient audio mixing.

Usage:
    python render_video_images.py /path/to/folder [--lut /path/to/file.cube]

─────────────────────────────────────────────────────────────────────────────
Intel Arc A750 QSV — Pipeline Rules (see render_video_videos.py for details)
─────────────────────────────────────────────────────────────────────────────
"""

import sys
import json
import re
import random
import subprocess
import time
import argparse
import requests
from pathlib import Path

RENDER_SERVER_URL = "http://192.168.0.14:8765"

# ── Local render codec profiles (Apple VideoToolbox — Mac Mini M2) ────────────
LOCAL_CODEC_YT = {
    "fps": 24, "cv": "hevc_videotoolbox", "bv": "4M",
    "ba": "256k", "pix_fmt": "yuv420p", "allow_sw": True, "q_v": 55,
}
LOCAL_CODEC_TT = {
    "fps": 30, "cv": "h264_videotoolbox", "bv": "5M",
    "ba": "192k", "pix_fmt": "yuv420p", "allow_sw": True, "q_v": 60,
}

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
AUDIO_EXTENSIONS = {".mp3", ".m4a", ".aac", ".wav", ".flac"}
TRANSITION_DURATION = 1.0

TRANSITIONS = [
    "fade", "fadeblack", "dissolve", "smoothleft", "smoothright",
    "zoomin", "circleopen", "fadewhite", "horzopen", "smoothup",
]

MIME_MAP = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".mp3": "audio/mpeg", ".m4a": "audio/mp4",
    ".aac": "audio/aac", ".wav": "audio/wav", ".flac": "audio/flac",
    ".cube": "application/octet-stream",
}

# ─────────────────────────────────────────────────────────────────────────────
# Parsing Timelines
# ─────────────────────────────────────────────────────────────────────────────

def parse_meta_scores(folder: Path) -> dict:
    """Parse position_score from _meta.md."""
    meta_file = next(folder.glob("*_meta.md"), None)
    if not meta_file:
        return {}
    content = meta_file.read_text(encoding="utf-8")
    scores = {}
    blocks = re.split(r'###\s+Image Prompt\s+', content, flags=re.IGNORECASE)
    for block in blocks[1:]:
        m_idx = re.match(r'^(\d+)', block)
        if not m_idx:
            continue
        idx = int(m_idx.group(1))
        m_score = re.search(r'\*\*position_score:\*\*\s*(\d+)', block, flags=re.IGNORECASE)
        if m_score:
            scores[idx] = int(m_score.group(1))
    return scores


def find_media_with_scores(folder: Path, scores: dict) -> list:
    """Scan folder for thumbnail and scene image files (PNG/JPG/WebP only).

    Accepted files:
      _NN_thumb.(png|jpg|webp) → is_thumb=True  (5s intro card)
      _NN_scene.(png|jpg|webp) → is_thumb=False (timeline image at position_score)

    Scene MP4s are ignored — use render_video_videos.py for Grok video renders.
    """
    media_data = []

    for f in sorted(folder.iterdir()):
        if not f.is_file():
            continue
        m = re.search(r'_(\d+)_(thumb|scene)', f.name.lower())
        if not m:
            continue
        idx = int(m.group(1))
        is_thumb = (m.group(2) == 'thumb')
        ext = f.suffix.lower()

        if ext not in IMAGE_EXTENSIONS:
            continue  # skip MP4s and anything else

        score = scores.get(idx, 0)
        media_data.append({
            "path": f,
            "idx": idx,
            "is_thumb": is_thumb,
            "score": score,
        })

    return media_data


def build_timeline(img_data: list, duration: float) -> list:
    """Map images to the audio timeline using position_score.

    Thumb image → 5s static title card at t=0.
    Scene images → placed at their position_score timestamps.
    """
    THUMB_INTRO = 5.0

    thumb_intro = next((img for img in img_data if img["is_thumb"]), img_data[0] if img_data else None)

    timeline_events = []
    for img in img_data:
        if img["is_thumb"]:
            continue
        target_t = (img["score"] / 100.0) * duration
        timeline_events.append({"img": img, "target": target_t})

    timeline_events.sort(key=lambda e: e["target"])

    if not timeline_events:
        return [{"img": thumb_intro, "start": 0.0, "end": duration}]

    first_target = timeline_events[0]["target"]
    events_natural_span = duration - first_target
    remaining = duration - THUMB_INTRO
    scale = remaining / events_natural_span if events_natural_span > 0 else 1.0

    segments = [{"img": thumb_intro, "start": 0.0, "end": THUMB_INTRO}]

    current = THUMB_INTRO
    for i, event in enumerate(timeline_events):
        if i < len(timeline_events) - 1:
            natural_dur = timeline_events[i + 1]["target"] - event["target"]
        else:
            natural_dur = duration - event["target"]

        seg_dur = max(10.5, natural_dur * scale)
        segments.append({"img": event["img"], "start": current, "end": current + seg_dur})
        current += seg_dur

    if segments:
        segments[-1]["end"] = duration

    return [s for s in segments if s["end"] > s["start"]]


def get_audio_duration(audio_path: Path) -> float:
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", str(audio_path)],
            capture_output=True, text=True, check=True
        )
        return float(json.loads(r.stdout)["format"]["duration"])
    except Exception:
        r = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_streams", str(audio_path)],
            capture_output=True, text=True, check=True
        )
        data = json.loads(r.stdout)
        for s in data.get("streams", []):
            if "duration" in s:
                return float(s["duration"])
    raise ValueError(f"Could not read audio duration for {audio_path.name}")


# ─────────────────────────────────────────────────────────────────────────────
# Building FFmpeg Chains (images only — no ambient audio)
# ─────────────────────────────────────────────────────────────────────────────

def get_shuffled_transitions(n_needed: int) -> list:
    if n_needed <= 0:
        return []
    res = []
    while len(res) < n_needed + 1:
        chunk = TRANSITIONS.copy()
        random.shuffle(chunk)
        if res and chunk[0] == res[-1]:
            chunk[0], chunk[-1] = chunk[-1], chunk[0]
        res.extend(chunk)
    return res[:n_needed]


def build_ff_commands(segments: list, fps: int, out_w: int, out_h: int, transitions: list,
                      lut_path: Path = None, duration: float = 0.0):
    """Build remote FFmpeg command (QSV) for static-image timeline."""
    td = TRANSITION_DURATION
    filter_parts = []
    unique_files = []
    file_to_idx = {}

    for seg in segments:
        p = seg["img"]["path"]
        if p not in file_to_idx:
            file_to_idx[p] = len(unique_files)
            unique_files.append(p)

    cmd_inputs = []
    for seg in segments:
        p = seg["img"]["path"]
        cmd_inputs += ["-r", str(fps), "-loop", "1", "-i", f"{{input_{file_to_idx[p]}}}"]

    for i in range(len(segments)):
        filter_parts.append(
            f"[{i}:v]"
            f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
            f"crop={out_w}:{out_h},setsar=1,fps={fps},"
            f"format=yuv420p[v{i}]"
        )

    if len(segments) == 1:
        last_label = "v0"
    else:
        last_label = "v0"
        for i in range(len(segments) - 1):
            t_name = transitions[i % len(transitions)]
            offset = segments[i]["end"] - td
            filter_parts.append(
                f"[{last_label}][v{i+1}]"
                f"xfade=transition={t_name}:duration={td:.3f}:offset={offset:.3f}"
                f"[x{i}]"
            )
            last_label = f"x{i}"

    lut_filter = f"lut3d={{lut_0}}," if lut_path else ""
    filter_parts.append(f"[{last_label}]{lut_filter}format=nv12[outv]")

    return cmd_inputs, ";".join(filter_parts), unique_files


def build_ff_commands_local(segments: list, fps: int, out_w: int, out_h: int, transitions: list,
                             lut_path: Path = None, duration: float = 0.0):
    """Build local FFmpeg command (VideoToolbox) for static-image timeline."""
    td = TRANSITION_DURATION
    filter_parts = []
    unique_files = []
    file_to_idx = {}

    for seg in segments:
        p = seg["img"]["path"]
        if p not in file_to_idx:
            file_to_idx[p] = len(unique_files)
            unique_files.append(p)

    cmd_inputs = []
    for seg in segments:
        p = seg["img"]["path"]
        cmd_inputs += ["-r", str(fps), "-loop", "1", "-i", str(p)]

    for i in range(len(segments)):
        filter_parts.append(
            f"[{i}:v]"
            f"scale={out_w}:{out_h}:force_original_aspect_ratio=increase:flags=lanczos,"
            f"crop={out_w}:{out_h},setsar=1,fps={fps},"
            f"format=yuv420p[v{i}]"
        )

    if len(segments) == 1:
        last_label = "v0"
    else:
        last_label = "v0"
        for i in range(len(segments) - 1):
            t_name = transitions[i % len(transitions)]
            offset = segments[i]["end"] - td
            filter_parts.append(
                f"[{last_label}][v{i+1}]"
                f"xfade=transition={t_name}:duration={td:.3f}:offset={offset:.3f}"
                f"[x{i}]"
            )
            last_label = f"x{i}"

    if lut_path:
        safe_lut = str(lut_path).replace("'", "\\'")
        lut_filter = f"lut3d='{safe_lut}',"
    else:
        lut_filter = ""
    filter_parts.append(f"[{last_label}]{lut_filter}format=yuv420p[outv]")

    return cmd_inputs, ";".join(filter_parts), unique_files


def build_render_job(segments, audio_path, duration, out_w, out_h, codec_info, lut_path: Path = None):
    transitions = get_shuffled_transitions(len(segments))
    cmd_inputs, fc, unique_files = build_ff_commands(
        segments, codec_info["fps"], out_w, out_h, transitions, lut_path, duration
    )

    all_uploads = unique_files + [audio_path]
    audio_idx = len(unique_files)

    if lut_path:
        lut_idx = len(all_uploads)
        all_uploads.append(lut_path)
        fc = fc.replace("{lut_0}", f"{{input_{lut_idx}}}")

    fade_out_st = max(0.0, duration - 3.0)
    af = f"afade=t=in:st=0:d=2,afade=t=out:st={fade_out_st:.3f}:d=3"

    cmd = ["-y", "-filter_threads", "8"]
    cmd += cmd_inputs
    cmd += ["-i", f"{{input_{audio_idx}}}"]
    cmd += ["-filter_complex", fc, "-map", "[outv]"]

    audio_stream = len(segments)
    cmd += ["-map", f"{audio_stream}:a", "-af", af]

    cmd += [
        "-c:v", codec_info["cv"],
        "-preset", codec_info.get("preset", "slow"),
        "-b:v", codec_info["bv"],
    ]
    if codec_info.get("profile"):
        cmd += ["-profile:v", codec_info["profile"]]
    if codec_info.get("level"):
        cmd += ["-level:v", codec_info["level"]]

    cmd += [
        "-c:a", "aac",
        "-b:a", codec_info["ba"],
        "-ar", "48000",
        "-t", str(duration),
        "-movflags", "+faststart",
        "{output_0}",
    ]
    return cmd, all_uploads


def build_local_render_job(segments: list, audio_path: Path, duration: float,
                            out_w: int, out_h: int, codec_info: dict,
                            output_path: Path, lut_path: Path = None) -> list:
    transitions = get_shuffled_transitions(len(segments))
    cmd_inputs, fc, unique_files = build_ff_commands_local(
        segments, codec_info["fps"], out_w, out_h, transitions, lut_path, duration
    )

    fade_out_st = max(0.0, duration - 3.0)
    af = f"afade=t=in:st=0:d=2,afade=t=out:st={fade_out_st:.3f}:d=3"

    cmd = ["ffmpeg", "-y", "-filter_threads", "4"]
    cmd += cmd_inputs
    cmd += ["-i", str(audio_path)]
    cmd += ["-filter_complex", fc, "-map", "[outv]"]

    audio_stream = len(segments)
    cmd += ["-map", f"{audio_stream}:a", "-af", af]

    cmd += [
        "-c:v", codec_info["cv"],
        "-b:v", codec_info["bv"],
        "-q:v", str(codec_info["q_v"]),
    ]
    if codec_info.get("allow_sw"):
        cmd += ["-allow_sw", "1"]
    cmd += [
        "-pix_fmt", codec_info["pix_fmt"],
        "-c:a", "aac",
        "-b:a", codec_info["ba"],
        "-ar", "48000",
        "-t", str(duration),
        "-movflags", "+faststart",
        str(output_path),
    ]
    return cmd


# ─────────────────────────────────────────────────────────────────────────────
# Server Execution
# ─────────────────────────────────────────────────────────────────────────────

def render_on_server(job_cmd: list, unique_uploads: list, output_filename: str, output_path: Path, duration: float):
    file_handles = []
    multipart_files = []
    job_id = None
    try:
        for fpath in unique_uploads:
            mime = MIME_MAP.get(fpath.suffix.lower(), "application/octet-stream")
            fh = open(fpath, "rb")
            file_handles.append(fh)
            multipart_files.append(("files", (fpath.name, fh, mime)))

        resp = requests.post(f"{RENDER_SERVER_URL}/render", files=multipart_files, timeout=120, data={
            "command": json.dumps(job_cmd),
            "outputs": json.dumps([output_filename]),
            "duration": str(duration),
        })
        resp.raise_for_status()
        job_id = resp.json()["job_id"]

        last_pct = -1
        while True:
            r = requests.get(f"{RENDER_SERVER_URL}/status/{job_id}", timeout=10)
            data = r.json()
            st = data["status"]
            pct = data.get("progress", 0)

            if pct != last_pct:
                bar = "#" * int(40 * pct / 100) + "-" * (40 - int(40 * pct / 100))
                print(f"\r  [{bar}] {pct:3d}%  {data.get('render_time_seconds', 0):.1f}s", end="", flush=True)
                last_pct = pct

            if st == "done":
                print()
                break
            elif st == "failed":
                print()
                raise RuntimeError(f"Server Render Exception: {data.get('error')}")
            time.sleep(2)

        print(f"  Downloading remote output -> {output_path.name}")
        dl_resp = requests.get(f"{RENDER_SERVER_URL}/download/{job_id}/{output_filename}", stream=True)
        dl_resp.raise_for_status()
        with open(output_path, "wb") as f:
            for chunk in dl_resp.iter_content(chunk_size=1024 * 1024):
                f.write(chunk)

    finally:
        for fh in file_handles:
            fh.close()
        if job_id:
            try:
                requests.delete(f"{RENDER_SERVER_URL}/job/{job_id}", timeout=5)
            except Exception:
                pass


def render_locally(cmd: list, duration: float):
    proc = subprocess.Popen(cmd, stderr=subprocess.PIPE, text=True, bufsize=1)
    time_pattern = re.compile(r'time=(\d{2}):(\d{2}):(\d{2})\.(\d{2})')
    last_pct = -1

    for line in proc.stderr:
        m = time_pattern.search(line)
        if m and duration > 0:
            h, mn, s, cs = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
            elapsed = h * 3600 + mn * 60 + s + cs / 100.0
            pct = min(100, int(elapsed / duration * 100))
            if pct != last_pct:
                bar = "#" * int(40 * pct / 100) + "-" * (40 - int(40 * pct / 100))
                print(f"\r  [{bar}] {pct:3d}%  {elapsed:.1f}s", end="", flush=True)
                last_pct = pct

    proc.wait()
    print()
    if proc.returncode != 0:
        raise RuntimeError(f"Local FFmpeg render failed (exit {proc.returncode})")


def human_size(p: Path):
    s = p.stat().st_size
    for u in ["B", "KB", "MB", "GB"]:
        if s < 1024:
            return f"{s:.1f} {u}"
        s /= 1024
    return f"{s:.1f} TB"


def check_server_with_retries(n: int = 3) -> bool:
    for attempt in range(1, n + 1):
        print(f"  [attempt {attempt}/{n}] Contacting render server...")
        try:
            resp = requests.get(f"{RENDER_SERVER_URL}/health", timeout=3)
            if resp.headers is not None:
                print("  Render server online.")
                return True
        except Exception:
            pass
        print(f"  Attempt {attempt} failed.")
        if attempt < n:
            time.sleep(2)
    print(f"  Render server unreachable after {n} attempts.")
    return False


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate YouTube + TikTok chapter videos (image timeline).")
    parser.add_argument("folder", help="Chapter output folder")
    parser.add_argument("--lut", metavar="FILE", help="Optional .cube LUT file for colour grading")
    args = parser.parse_args()

    folder = Path(args.folder).expanduser().resolve()
    lut_path = Path(args.lut).expanduser().resolve() if args.lut else None

    if lut_path and not lut_path.exists():
        print(f"Error: LUT file not found: {lut_path}")
        sys.exit(1)

    print(f"\nAnalyzing: {folder}")
    if lut_path:
        print(f"  LUT      : {lut_path.name}")

    use_remote = check_server_with_retries(3)
    if not use_remote:
        print("  Falling back to local render (Apple VideoToolbox — Mac Mini M2).")

    audio = next((f for f in folder.iterdir() if f.suffix.lower() in AUDIO_EXTENSIONS), None)
    if not audio:
        print("Error: Audio missing.")
        sys.exit(1)

    scores = parse_meta_scores(folder)
    media_data = find_media_with_scores(folder, scores)

    if not media_data:
        print("Error: No thumbnail or scene images (PNG/JPG/WebP) found.")
        print("  Run generate_image.py first to generate Gemini scene images.")
        sys.exit(1)

    duration = get_audio_duration(audio)
    segments = build_timeline(media_data, duration)

    print(f"\n  Audio    : {audio.name} ({duration / 60:.1f} min)")
    print(f"  Timeline Segments ({len(segments)} blocks, min 10.5s each):")
    for i, s in enumerate(segments):
        label = "thumb" if s['img']['is_thumb'] else "scene"
        print(f"    [{i+1}] {s['start']:>6.1f}s -> {s['end']:>6.1f}s | {s['img']['path'].name} [{label}]")

    thumb_img = next((m["path"] for m in media_data if m["is_thumb"]), media_data[0]["path"])
    stem = re.sub(r'_\d+_(thumb|scene).*', '', thumb_img.stem)

    out_yt = folder / f"{stem}_youtube.mp4"
    out_tt = folder / f"{stem}_tiktok.mp4"

    if out_yt.exists():
        print(f"  Skipping YouTube render — {out_yt.name} already exists.")
    if out_tt.exists():
        print(f"  Skipping TikTok render  — {out_tt.name} already exists.")
    yt_req = not out_yt.exists()
    tt_req = not out_tt.exists()

    if yt_req:
        if use_remote:
            print(f"\n[1/2] YouTube Rendering | 1440x2560 (2K) | av1_qsv | 24 FPS  [REMOTE]")
            cmd, files = build_render_job(segments, audio, duration, 1440, 2560, {
                "fps": 24, "cv": "av1_qsv", "bv": "3M", "ba": "256k", "preset": "4"
            }, lut_path)
            render_on_server(cmd, files, out_yt.name, out_yt, duration)
        else:
            print(f"\n[1/2] YouTube Rendering | 1440x2560 (2K) | hevc_videotoolbox | 24 FPS  [LOCAL]")
            cmd = build_local_render_job(segments, audio, duration, 1440, 2560, LOCAL_CODEC_YT, out_yt, None)
            render_locally(cmd, duration)
        print(f"  Saved: {human_size(out_yt)}")

    if tt_req:
        if use_remote:
            print(f"\n[2/2] TikTok Rendering | 1080x1920 | h264_qsv | 30 FPS  [REMOTE]")
            cmd, files = build_render_job(segments, audio, duration, 1080, 1920, {
                "fps": 30, "cv": "h264_qsv", "bv": "5M", "ba": "192k",
                "profile": "high", "level": "4.1"
            }, lut_path)
            render_on_server(cmd, files, out_tt.name, out_tt, duration)
        else:
            print(f"\n[2/2] TikTok Rendering | 1080x1920 | h264_videotoolbox | 30 FPS  [LOCAL]")
            cmd = build_local_render_job(segments, audio, duration, 1080, 1920, LOCAL_CODEC_TT, out_tt, None)
            render_locally(cmd, duration)
        print(f"  Saved: {human_size(out_tt)}")


if __name__ == "__main__":
    main()
